Oculo/MainViewController.swift
- 버튼에 테두리를 그렸습니다.
- 버튼을 클릭하면 배경 색상이 변경됩니다.
=> 버튼 모양 수정, 클릭 이벤트 추가

Conventions.md
- 컨벤션 작성 완성
- conventions.md 파일 내용 수정 및 보완
- 컨벤션 내용을 전반적으로 정리했으니 꼭 읽어보시기 바랍니다.
=> [Docs] #21 Conventions.md 업데이트

Conventions.md
- Conventions.md 파일 내 목차 작성
- 목차 추가
- 별 것 업습니다.
=> [Docs] # 22 Conventions.md 내 목차 추가

Conventions.md
빠진 링크를 추가했습니다.
- 목차 내 몇몇 링크 수정
- 빠진 링크 추가
- 특별한 변경이 없습니다.
=> [Docs] #34 Conventions.md 내 목차 수정

Oculo/MainViewController.swift
- .clear -> .black으로 바꿔놓은 게 어느 새 다시 .clear로 돌아가 있었다
- .clear -> .black 수정 완료했습니다
- ViewController -> MainViewController로 명칭 변경했습니다
- 로직 변경은 없습니다.
=> [Feat] 터치_씹힘_ViewController_이름_변경_진짜_최종(feat.레트로)

Oculo/MainViewController.swift
- 분명 변경사항이 적용됐을 줄 알았는데 적용이 안 됐습니다.
- .clear -> .black 다시 적용했습니다.
- 이번엔 괜찮겠져
=> [Fix] #44 터치 영역 버그 수정

Oculo/MainViewController.swift
- ViewController -> MainViewController 변경 사항 미적용을 발견했습니다
- ViewController -> MainViewController로 명칭 변경 완료했습니다
- 로직 변경은 없습니다. 빌드 다시 해 보고 올리니 이번에는 괜찮을 것 같습니다.
=> [Fix] #44 ViewController -> MainViewController

Oculo/MainViewController.swift
- 현재 MainViewController 버튼이 Frame의 고정된 위치로 이루여져 있습니다.
- Constraints를 통해 위치 관계를 표현하는것이 더 명확하다고 판단하여 해당 부분을 refactoring할 예정입니다.
- 또한 버튼의 변수명도 일부 변경 예정입니다. (TextReadingButton -> textReaderButton )
- UIButton 함수 return에서 분리
- Frame -> constraints로 전환
- Setting Button 위치 변경 (우->좌)
- 사용하지 않는 이전 주석 제거
- UI와 관련된 다양한 이야기를 해주시면 Design 이슈 생성시 반영하도록 하겠습니다.
=> [Refactor] MainView 버튼 구조 Frame -> Constrains 전환 #54

Oculo.xcodeproj/project.pbxproj, Oculo/TextReaderViewController.swift
- Text Reading 기능을 실행할 View Controller File이 필요합니다.
- UIViewController 파일만 생성하여 추가하였습니다.
- 내용은 파일 추가 후 진행하겠습니다.
=> [Add] TextReaderViewController추가 #57

Oculo.xcodeproj/project.pbxproj, Oculo/MainViewController.swift, Oculo/SettingViewController.swift, Oculo/Utilities/StringExtension.swift, Oculo/Utilities/en.lproj/Localizable.strings, Oculo/Utilities/ko.lproj/Localizable.strings
- 영어권 사용자들에게 맞는 언어를 보여주기 위해 Localization 하였습니다.
- 영어 사용자와 한글 사용자에게 맞는 Localizable 파일을 추가하였습니다. 
- enum과 extension을 이용해서 사용하기 편하게 만들었습니다.
- enum을 사용하긴 했지만 조금 더 효율적으로 작성할 수 있을 것 같은데, 좋은 방법이 떠오르지 않네요.  
조금 더 좋은 방법이 있으시면 조언 부탁드립니다! 리뷰도 환영합니다!
- 현재 사용자들이 보기에 좋은 [UX](https://github.com/ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS/compare/Localization?expand=1#diff-cd15c27a63bae0019119c86d974676797c19d8abb9c8a415bf0a437f278faf7eR12)가 아닌 부분이 있습니다. 추후에 상의하여 변경하도록 하겠습니다.
=> [Feat] #67 Localizing 언어 변환

LICENSE
- 라이센스 업데이트
- 라이센스 파일을 업데이트 했습니다.
- 단순 작업입니다.
=> [Docs] 라이센스 변경

.gitignore
- Cocoapods 사용 예정으로 깃 이그노어 파일 업데이트 필요함
- 해당 내용을 반영하여 수정했습니다.
- 코코아팟 사용 방법은 리드미에 업데이트하도록 하겠습니다.
=> [Chore] 깃 이그노어 파일 업데이트

Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
- ObjectDetectionViewController의 공백 및 주석 오타, 인덴트 수정 필요
- 공백 제거 및 주석에 있던 오타 수정
- 잘못된 인덴트 수정
- 지난번 코드리뷰때 받은 오류사항 수정했습니다. 다만 pauseARSession의 경우에는 ARSession이 가지고 있는 기본 메서드가 stop이 아닌 pause로 정의 되었기에 pauseARSession 그대로 유지했습니다.
=> [Chore] #63 #82 whitespace 제거 및 주석, 인덴트 수정

Oculo/TextReaderViewController.swift, Oculo/Utilities/TTSTool.swift
- Text Reader 기능 사용시, TTS와 Voiceover의 소리가 동시에 들리는 이슈가 있습니다.
- 설명 문구 등 불필요한 요소를 읽어서 실제 사용시 방해가 됩니다.
- VoiceOver를 킨 경우 TTS가 아닌 VoiceOver가 문자열을 읽습니다.
- 불필요한 요소를 제거하였습니다.
- TTS는 디버깅용으로 남기고 VocieOver를 적극 활용하는건 어떨까요?
=> [Feat] #95 Tts, VoiceOver 관련 추가 설정

Oculo.xcodeproj/project.pbxproj, Oculo/DeepSORT/ObjectTracker.swift
- 지난 PR 후 빌드에러 해결
- 사용 불가능한 파일 주석처리
- 사용 불가능한 파일 Reference, Project 파일에서 제거
- YOLO 모델을 제외하고는 빌드 되는 파일로만 PR 날려주시면 감사하겠습니다. 만약 주석처리를 해야한다면 직접 주석처리하고 올려주세요
- 만약 필요없는 파일을 삭제할 경우 프로젝트에서도 삭제 바랍니다. 프로젝트에 Reference가 남아있으면 빌드가 안됩니다. @garlicvread 
- 브랜치 이름은 실수했습니다. ㅎㅎ 어차피 삭제할꺼니까..
=> [Fix] 빌드 안되는 에러 해결

Oculo.xcodeproj/project.pbxproj, Oculo/DeepSORT/ObjectTracker.swift, Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
- YOLO와 depthMap의 좌표 Mapping 필요
- 예측한 Box 내의 최소 거리값 반환 필요
- ARSession 내에서 YOLO 좌표를 depthMap 좌표로 변환
- 예측한 Box 내에서 최소 거리값의 좌표: 깊이 딕셔너리로 반환
- 이해 안되는 부분이나 수정사항 있으면 코멘트 부탁드립니다.
=> [Feat] #104 좌표변환 및 최소값 반환 기능 추기

Oculo/EnvironmentReader/EnvironmentReaderViewController.swift, Oculo/EnvironmentReader/Plane.swift
- 현재 문 인식 관련 모델이 없는 관계로 SceneKit에 있는 문 인식 기능을 활용한 중입니다.
- SceneKit에서 인식한 문과 아이폰 카메라의 거리를 측정하고 표시하는 기능이 필요합니다.
- 문과 사람 사이의 거리를 AR을 통해서 확인할 수 있습니다. 단위는 미터입니다.
- AR기능 사용 중 에러가 발생할 경우 음성으로 안내합니다.
- 음성으로 거리를 안내할 경우, 보폭 단위로 변경이 필요합니다.
- 문 인식 모델이 완성될 경우 교체될 예정입니다.
=> [Feat] AR 버전 문과 카메라의 거리 측정 및 표시, AR기능 사용 중 문제 발생시 말하기 기능

Oculo.xcodeproj/project.pbxproj, Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
- ARSession 내 Object Detaction 및 BoundingBox 처리시 영상 처리 프레임이 급격히 떨어지는 문제가 있습니다.
- 사용자에게 조금 더 명확한 정보 전달을 위해 개선이 필요합니다.
- Object의 Bounding Box 처리 시 UIImage로 변경하는 부분의 로직을 개선하였습니다.
- 
- 보여지는 프리뷰를 캡처하는 방식이 아닌 ARFrame을 프리뷰의 사이즈에 맞게 조정하는 방식으로 구현하였습니다.
- 다른 로직에서도 개선이 필요합니다.
=> [Feat] #106 ARSession Image capture 리팩토링

Conventions.md, Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
- 실수로 whitespace 추가됨
- 변수명에 오타 존재
- whitespace 제거
- 변수명에서 typo 제거
- 기타 한글 맞춤법도 일부 수정했습니다.
=> [Chore] whitespace 및 typo 수정

Oculo.xcodeproj/project.pbxproj, Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
- 여러개의 문이 촬영될 경우 안내에 문제가 발생합니다.
- 기타 사용성 개선에 대한 필요성이 있습니다.
- 화면을 터치하면 다시 문 인식을 수행합니다.
- 처음 인식된 문을 끝까지 tracking 합니다.
- 개선점이 있다면 언제든지 말씀해주세요!
=> [Feat] 복수의 문 인식 방법 개선, 인식 초기화 버튼 배치

Oculo/ObjectRecognizer/ObjectDetectionViewController.swift
- 가장 가까이있는 물체의 좌표와 라벨을 읽어주고 싶었습니다.
- minValueDictionary 의 구성을 변경했습니다.
- minValueDictionary 가 비어있지 않고, synthesizer가 말하고있지않을때 가장 가까이에있는 물체의 좌표와 라벨을 synthesizer가 읽어주게 했습니다.
- @hotsunnyday  @realmountain1129  감사합니다.
=> [Feat] 가장 가까이 있는 물체의 좌표와 라벨을 synthesizer 로 읽어주는 기능입니다. #131

Oculo/MainViewController.swift, Oculo/ObjectRecognizer/ObjectDetectionViewController.swift, Oculo/Utilities/SoundManager.swift
- MainView에서 작동하는 근접센서를 네비게이션(ObjectRecognizer)으로 변경하였습니다.
- 속도에 관한 피드백도 확인해 변경하였습니다.
- 근접 센서가 Main에서 ObjectRecognizer에서 작동하도록 변경하였습니다.
- TTS 속도를 향상시켰습니다. (VoiceOver는 앱에서 속도 설정불가합니다.)
- 멘트를 콘솔에 print하는 방법에서 TTS로 말하도록 변경하였습니다.
- TTS 속도 관련 이슈를 본 것 같은데 해당 pull request에서 변경하였습니다.
=> [Feat] #140 근접센서 동작 ObjectRecognizer로 변경, 근접센서 관련 음성안내 추가, TTS 속도 조절

Oculo/MainViewController.swift
- 알림창이 나오지 않았음
- 누락된 present 코드 추가
- 큰 실수 했네요, 죄송합니다. Thank You @mizz0224 !!
=> [Fix] 알림창 나오지 않는 오류 수정

Oculo.xcodeproj/project.pbxproj, Oculo/EnvironmentReader/EnvironmentReaderViewController.swift, Oculo/EnvironmentReader/Plane.swift, Oculo/Info.plist, Oculo/MainViewController.swift, Oculo/ObjectRecognizer/ObjectDetectionViewController.swift, Oculo/Oculo.entitlements, Oculo/Utilities/HealthkitManager.swift
- HealthKit을 용도 외로 사용했다는 이슈로 인해 앱 심사가 거절되었습니다.
- 앱 심사 이슈로 인해 HealthKit 관련 내용을 제거하였습니다.
- 보폭을 70cm로 일괄고정 하였습니다.
- gps 데이터도 용도 외로 사용한다고 따질것 같아서 이런 방식으로 처리했습니다.
=> [Fix] HealthKit 제거

Oculo.xcodeproj/project.pbxproj, Oculo/LicenseVIewController.swift, Oculo/MainViewController.swift, Oculo/ObjectRecognizer/ObjectDetectionViewController.swift, Oculo/SettingViewController.swift, Oculo/Utilities/SoundManager.swift, Oculo/Utilities/StringExtension.swift, Oculo/Utilities/en.lproj/Localizable.strings, Oculo/Utilities/ko.lproj/Localizable.strings
- 본인이 원하는 말하기속도를 조절하고 싶어하는 사용자의 니즈를 충족하기위해 말하기 속도를 조절하는 기능을 만들었습니다.
- 메인페이지에서 최초구동인지를 판별해서 최초구동일시 말하기속도를 0.8로 저장
- soundManger에서 유저디폴트에서 speakingRate를 읽어오는 기능
- setting view에서 license view 분리
- setting view에서 말하기 속도 조절하는 custom cell 추가
- setting view에서 화면이 깨지는 현상 수정
- 꼼꼼한 테스트 부탁드립니다.
=> Feat/setting view and control tts speed #140

Oculo.xcodeproj/project.pbxproj
- 버전을 판올림하면서 프로젝트에서 버전을 변경해 줄 필요가 있었음
- xcode project target 에서 identify 란에 있는 버전을 1.0 -> 1.1로 변경
- 코드 수정은 없고 버전 변경만 있습니다
=> [Build] 버전 변경

Oculo/ObjectRecognizer/ObjectDetectionViewController.swift, Oculo/Utilities/SoundManager.swift
- VoiceOver를 작동시키고 네비게이션 기능을 사용하면 음성이 깨져서 들리는 문제가 발생합니다.
- VoiceOver를 사용해도 TTS로 말하게 하는 기능 생성
- ObjectDetectionViewController에 적용
- 추가로 TTS문구 출력하는 디버깅용 기능들 제거했습니다.
- 앱스토어에 반영도 부탁드려요~
=> [Fix] VoiceOver 충돌 해결

Oculo/DeepSORT/KalmanFilter/KalmanFilter.swift, Oculo/DeepSORT/KalmanFilter/KalmanMatrix.swift, Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
- 칼만 필터에 사용되는 KalmanInput, 즉 행렬 연산을 위한 여러 코드가 추가됨
- KalmanMatrix.swift 파일 추가
- 보고 이해 안 되는 부분 있으시면 말씀해 주세용!
=> [Feat] 칼만 행렬 구조체 추가

Oculo/DeepSORT/KalmanFilter/KalmanFilter.swift, Oculo/EnvironmentReader/EnvironmentReaderViewController.swift
- 칼만 필터 코드 및 주석 임시 완성
- KalmanFilter.swift 파일을 추가했습니다.
- 이해가 안 되는 부분이 있으면 같이 이야기 해 보면 좋을 것 같습니다!
=> [Feat] 칼만 필터 업데이트

Oculo.xcodeproj/project.pbxproj, Oculo/SceneDelegate.swift
- 우리의 어플은 지속적으로 카메라와 음성을 사용해야하는데 이전에는 사용 중에도 화면의 자동잠금 기능이 작동했었음
- 앱이 실행중일 때 외부 입력이 없어도 자동잠금이 방지되는 코드 추가
- 버전 변경
- 기본적으로 지원하는 잠금 방지 코드이니 빠르게 approve 해주시면 감사하겠습니다
=> [Feature] 스크린 자동잠금 방지
